<a href="https://colab.research.google.com/github/KayalvizhiT513/TNEA-seat-matrix-analysis/blob/main/prev_prov_alot_vs_seat_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [24]:
ppr_df = pd.read_excel('/content/drive/MyDrive/TNEA Seat Matrix 2025/CSE(OC).xlsx')
ppr_df = ppr_df.dropna(subset=['OC 2024', 'OC 2023'])
ppr_df

,College Code,College Name,Course Code,OC 2024,OC 2023,OC 2022,OC 2021,OC AVG,PUBLIC PERCEPTION RANK
0,1,"University Departments of Anna University, Che...",CS,200.0,200.0,200.0,199.000,199.75,1
1,1,"University Departments of Anna University, Che...",CM,199.5,199.5,199.5,198.000,199.13,2
2,2006,"PSG College of Technology (Autonomous), Peelam...",CM,198.5,199.0,199.5,197.500,198.63,3
3,4,"University Departments of Anna University, Che...",CS,199.0,199.0,199.0,197.175,198.54,4
4,1315,Sri Sivasubramaniya Nadar College of Engineeri...,CS,198.5,199.0,198.5,197.000,198.25,5
...,...,...,...,...,...,...,...,...,...
389,4677,Lourdes Mount College of Engineering and Techn...,CS,129.5,93.5,96.5,NaN,106.50,390
390,4978,"Udaya School of Engineering, Ammandivilai Post...",CS,83.0,95.5,96.0,148.095,105.65,391
393,5533,Karaikudi Institute of Technology and Karaikud...,CS,88.5,116.5,NaN,NaN,102.50,394
395,1518,Thiruvalluvar College of Engineering and Techn...,CS,112.0,93.0,90.0,NaN,98.33,396
399,2717,"Sasurie College of Engineering, Vijayamangalam...",CS,114.5,94.0,80.0,NaN,96.17,400

In [25]:
count = 0
ppr_chennai_df = pd.DataFrame()
for index, row in ppr_df.iterrows():
    #print(row) # Uncomment this line if you want to see the row data
    clg_name = row['College Name']
    if 'chennai' in clg_name.lower():
        count += 1
        ppr_chennai_df = pd.concat([ppr_chennai_df, row.to_frame().T])
print(count)

55

In [26]:
ppr_chennai_df

,College Code,College Name,Course Code,OC 2024,OC 2023,OC 2022,OC 2021,OC AVG,PUBLIC PERCEPTION RANK
0,1,"University Departments of Anna University, Che...",CS,200.0,200.0,200.0,199.0,199.75,1
1,1,"University Departments of Anna University, Che...",CM,199.5,199.5,199.5,198.0,199.13,2
3,4,"University Departments of Anna University, Che...",CS,199.0,199.0,199.0,197.175,198.54,4
5,4,"University Departments of Anna University, Che...",CM,198.0,198.5,198.5,196.5,197.88,6
12,1399,"Chennai Institute of Technology, Puduper Villa...",CS,194.0,195.5,195.5,193.095,194.52,13
14,1219,Sri Venkateswara College of Engineering (Auton...,CS,190.5,193.5,195.5,193.79,193.32,15
20,1450,Loyola ICAM College of Engineering and Technol...,CS,189.0,191.0,191.0,192.0,190.75,21
26,1317,St. Joseph's College of Engineering (Autonomou...,CS,185.0,186.5,190.0,191.21,188.18,27
29,1419,"Sri Sai Ram Enginering College (Autonomous), W...",CS,186.0,185.0,190.0,190.525,187.88,30
30,1304,"Easwari Engineering College (Autonomous), Rama...",CS,183.5,185.0,189.5,190.945,187.24,31
38,1414,Prince Shri Venkateshwara Padmavathy Engineer...,CS,193.0,193.5,180.065,175.91,185.62,39
41,1309,"Meenakshi Sundararajan Engineering College, Ko...",CS,179.5,184.5,187.0,188.075,184.77,42
46,1422,SRM Valliammai Engineering College (Autonomous...,CS,182.0,180.5,184.46,185.515,183.12,47
52,1324,Sri Sai Ram Institute of Technology (Autonomou...,CS,178.5,177.0,182.5,186.0,181.0,53
58,1026,"University College of Engineering, Kancheepura...",CS,178.5,172.5,181.5,185.755,179.56,59
59,1149,"St. Josephs Institute of Technology, Jeppiaar ...",CS,176.0,174.0,182.385,184.935,179.33,60
64,1210,"Panimalar Engineering College (Autonomous), Na...",CS,172.5,173.0,180.0,187.405,178.23,65
70,1120,"Velammal Engineering College (Autonomous), Amb...",CS,173.0,168.5,178.0,185.205,176.18,71
79,1118,Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunth...,CS,167.5,168.0,173.5,181.86,172.72,80
82,1311,"K C G College of Technology, Karappakkam, Chen...",CS,169.5,166.5,173.0,180.735,172.43,83
85,1442,Prince Dr. K Vasudevan College of Engineering ...,CS,187.0,169.98,162.285,169.095,172.09,86
88,1306,"Jeppiaar Engineering College, Old Mahabalipura...",CS,167.0,164.0,173.5,181.92,171.61,89
102,1122,Vel Tech High Tech Dr. Rangarajan Dr. Sakuntha...,CS,167.0,163.0,165.5,179.97,168.87,103
104,1310,Misrimal Navajee Munoth Jain Engineering Colle...,CS,164.0,160.5,169.5,177.35,167.84,105
112,1225,"Loyola Institute of Technology, Mevaloorkuppam...",CS,165.5,158.5,164.5,174.9,165.85,113
114,1114,"S A Engineering College (Autonomous), Thiruver...",CS,160.0,159.0,163.0,178.68,165.17,115
116,1237,"Velammal Institute of Technology, Chennai-Kolk...",CS,158.5,158.5,163.5,179.5,165.0,117
119,1307,"Jerusalem College of Engineering (Autonomous),...",CS,159.5,160.5,162.0,176.155,164.54,120
122,3019,"University College of Engineering, Panruti, Ch...",CS,162.5,157.0,163.0,174.13,164.16,123
142,1509,"Meenakshi College of Engineering, Vembuliamman...",CS,155.5,152.0,152.5,175.5,158.88,143
160,1420,"Tagore Engineering College, Rathnamangalam, Va...",CS,152.0,141.0,155.0,171.855,154.96,161
161,1411,"Madha Engineering College, Kundrathur, Chennai...",CS,141.0,178.25,138.0,161.93,154.8,162
162,1238,"G R T Institute of Engineering and Technology,...",CS,144.5,149.0,151.5,173.0,154.5,163
177,1101,"Aalim Muhammed Salegh College of Engineering, ...",CS,148.0,140.5,147.5,171.605,151.9,178
183,1405,"Dhanalakshmi College of Engineering, Manimang...",CS,148.0,144.5,144.5,168.38,151.35,184
188,1217,Sree Sastha Institute of Engineering and Techn...,CS,143.0,143.0,143.0,174.275,150.82,189
193,3804,"Arasu Engineering College, Chennai Main Road,...",CS,141.0,142.5,151.5,163.11,149.53,194
195,1431,New Prince Shri Bhavani College of Engineering...,CS,140.0,141.5,143.5,170.9,148.98,196
199,1127,St. Peters College of Engineering and Technolo...,CS,138.5,143.5,142.5,169.07,148.39,200
201,1322,Dhanalakshmi Srinivasan College of Engineering...,CS,133.5,139.0,148.0,171.5,148.0,202
207,1424,"Dhaanish Ahmed College of Engineering, Padappa...",CS,152.0,132.0,138.5,166.0,147.13,208
210,3829,"M.A.M. College of Engineering and Technology, ...",CS,137.5,146.0,142.0,161.85,146.84,211
213,1202,"D M I College of Engineering, Palanchoor, Nazr...",CS,144.0,138.0,139.5,164.525,146.51,214
214,1452,"PERI Institute of Technology, Mannivakkam, Wes...",CS,142.0,131.0,142.0,170.745,146.44,215
232,1106,"Jaya Engineering College, Thirunindravur, Chen...",CS,130.0,140.0,139.0,162.475,142.87,233
240,1228,"Alpha College of Engineering, No.34, Udayavar ...",CS,127.0,132.5,134.0,169.585,140.77,241
253,1123,"Gojan School of Business and Technology, Alama...",CS,134.0,134.5,132.0,154.78,138.82,254
279,1523,Global Institute of Engineering and Technology...,CS,122.5,128.0,123.0,160.405,133.48,280
287,1218,"Sri Muthukumaran Institute of Technology, Near...",CS,119.0,119.5,116.5,171.1,131.53,288
316,1133,"Annai Veilankannis College of Engineering, Gan...",CS,107.0,129.5,120.0,149.945,126.61,317
321,1407,"G K M College of Engineering and Technology, ...",CS,126.0,116.5,98.0,163.75,126.06,322
322,5942,"Ultra College of Engineering and Technology, ...",CS,113.0,112.5,114.5,159.32,124.83,323
323,1426,"Sri Ramanujar Engineering College, Vandalur, K...",CS,129.5,102.5,124.0,141.135,124.28,324
330,1416,"Jaya Sakthi Engineering College, Thirunindravu...",CS,105.0,122.0,108.0,156.285,122.82,331
353,1437,"Rrase College of Engineering, Padappai, Chenna...",CS,132.0,124.0,98.0,NaN,118.0,354

In [33]:
ppr_chennai_df.loc[ppr_chennai_df['College Code'] == 1225, 'College Name']

112    Loyola Institute of Technology, Mevaloorkuppam...
Name: College Name, dtype: object

In [35]:
count = 0

for index, row in ppr_df.iterrows():
    #print(row) # Uncomment this line if you want to see the row data
    clg_name = row['College Name']
    if 'thiruvallur' in clg_name.lower():
        count += 1
        print(clg_name)

count

R M K Engineering College (Autonomous), Kavaraipettai, Gummidipoondi, Thiruvallur District 601206
R M D Engineering College (Autonomous), Kavaraipettai, Gummidipoondi, Thiruvallur District 601206
R M K College of Engineering and Technology (Autonomous), Puduvoyal, Gummidipoondi Taluk, Thiruvallur District 601206
Sri Venkateswara College of Engineering and Technology, Thirupachur, Thiruvallur District 631203
Velammal Institute of Technology, Chennai-Kolkatta Highway, Panchetti Village, Ponneri Taluk, Thiruvallur District 601204
Prathyusha Engineering college, Aranvoyalkuppam, Thiruvallur District 602025
G R T Institute of Engineering and Technology, GRT Mahalakshmi Nagar, Chennai-Tirupathi Highway, Tiruttani Taluk, Thiruvallur District 631209
Sri Ram Engineering College, Perumalpattu, Veppampattu (R S), Thiruvallur District 602 024
J N N Institute of Engineering, Ushaa Garden, Kannigaipair Village, Uthukottai Taluk, Thiruvallur District 601102
T J S Engineering College, Peruvoyal, Near Kavaraipettai, Gummidipoondi Taluk, Thiruvallur District 601206
Sri Venkateswara Institute of Science and Technology, Kozhundalur, Thiruvallur District 631203

11

In [28]:
count = 0

for index, row in ppr_df.iterrows():
    #print(row) # Uncomment this line if you want to see the row data
    clg_name = row['College Name']
    if 'chengalpattu' in clg_name.lower():
        count += 1
        print(clg_name)

count

University Departments of Anna University, Chennai - MIT Campus, Chrompet, Tambaram Taluk, Chengalpattu District 600 044
Sri Sivasubramaniya Nadar College of Engineering (Autonomous), Kalavakkam, Old Mahabalipuram Road (OMR), Chengalpattu District 603110
University Departments of Anna University, Chennai - MIT Campus, Chrompet, Tambaram Taluk, Chengalpattu District 600 044
Mohammed Sathak A J College of Engineering, Old Mahabalipuram Road (OMR), Egattur, Chengalpattu District 603103
Agni College of Technology, Old Mahabalipuram Road (OMR), Thalambur Village, Chengalpattu District 603103
Adhiparasakthi Engineering College, Melmaruvathur, Chengalpattu District 603319
Anand Institute of Higher Technology, Old Mahabalipuram Road (OMR), Kazhipattur, Chengalpattu District  603103
Karpaga Vinayaga College of Engineering and Technology, Palayanoor Post, Maduranthagam Taluk, Chengalpattu District 603308
Asan Memorial College of Engineering and Technology,Chengalpattu-603 001.

9

In [ ]:
prov_alot_2024_3_df = pd.read_excel('/content/GENERAL_ACADEMIC_ROUND3_2024.pdf')

# Task
Convert the PDF file "/content/drive/MyDrive/data/us-treasury-rates.pdf" to an Excel file by extracting and merging all tables from each page.

## Install necessary library

### Subtask:
Install a library that can read PDF files and extract tables. `tabula-py` is a good option for this.

**Reasoning**:
Install the `tabula-py` library using pip.

In [36]:
%pip install tabula-py

Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.11/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.11/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 95.2 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.10.0

## Extract tables

### Subtask:
Read the PDF file and extract tables from each page using the installed library.

**Reasoning**:
Read the PDF file and extract tables from each page using the installed library.

In [41]:
from tabula import read_pdf

pdf_path = '/content/GENERAL_ACADEMIC_ROUND3_2024.pdf'
tables = read_pdf(pdf_path, pages='all', multiple_tables=True)

## Combine tables

### Subtask:
Concatenate or merge the extracted tables from all pages into a single DataFrame.

**Reasoning**:
Concatenate the list of DataFrames into a single DataFrame using `pd.concat()`.

In [43]:
combined_df = pd.concat(tables)
display(combined_df.head())

,S NO,APPLN NO,NAME OF THE CANDIDATE,DOB,COMMU\rNITY,AGGR\rMARK,RANK,COLLEGE\rCODE,BRANCH\rCODE,ALLOTTED\rCATEGORY
0,1,447808,LIBNA ANSU S,02-12-2004,MBC,194.5,2974A,4944,AD,MBC
1,2,409895,VIJAY R,08-12-2006,MBC,192.5,4970,2753,CS,OC
2,3,403726,BHARATHAN R,25-09-2007,MBC,190.0,7992,1420,IT,MBC
3,4,305181,PRAVEENKUMAR E,09-04-2007,MBC,189.5,9087,3016,EC,OC
4,5,288667,ADHILAKSHMI R,31-12-2006,MBC,187.5,11852,1520,AD,MBC

## Save to Excel

### Subtask:
Save the combined DataFrame to an Excel file.

**Reasoning**:
Save the `combined_df` to an Excel file named `combined_tables.xlsx`.

In [44]:
combined_df.to_excel('GENERAL_ACADEMIC_ROUND3_2024.xlsx', index=False)

In [47]:
combined_df.columns

Index(['S NO', 'APPLN NO', 'NAME OF THE CANDIDATE', 'DOB', 'COMMU\rNITY',
       'AGGR\rMARK', 'RANK', 'COLLEGE\rCODE', 'BRANCH\rCODE',
       'ALLOTTED\rCATEGORY'],
      dtype='object')

In [48]:
combined_df.reindex(columns=['S NO', 'APPLN NO', 'NAME OF THE CANDIDATE', 'DOB', 'COMMU\rNITY',
       'AGGR\rMARK', 'RANK', 'COLLEGE\rCODE', 'BRANCH\rCODE',
       'ALLOTTED\rCATEGORY'])

,S NO,APPLN NO,NAME OF THE CANDIDATE,DOB,COMMU\rNITY,AGGR\rMARK,RANK,COLLEGE\rCODE,BRANCH\rCODE,ALLOTTED\rCATEGORY
0,1,447808,LIBNA ANSU S,02-12-2004,MBC,194.5,2974A,4944,AD,MBC
1,2,409895,VIJAY R,08-12-2006,MBC,192.5,4970,2753,CS,OC
2,3,403726,BHARATHAN R,25-09-2007,MBC,190.0,7992,1420,IT,MBC
3,4,305181,PRAVEENKUMAR E,09-04-2007,MBC,189.5,9087,3016,EC,OC
4,5,288667,ADHILAKSHMI R,31-12-2006,MBC,187.5,11852,1520,AD,MBC
...,...,...,...,...,...,...,...,...,...,...
30,46719,407752,SELVAKUMAR V,28-09-2006,SC,79.0,197588,2636,AD,SC
31,46720,365570,PETHURAJA M,04-11-2005,MBC,79.0,197589,2737,EE,MBC
0,46721,452986,DELHI GANESH M,05-06-2003,SCA,79.0,197590,1438,CS,OC
1,46722,326014,CHANDRASEKAR C,16-08-2005,MBC,77.5,197600,2648,AU,MBC
2,46723,451180,SINGARAM V,15-11-2007,MBC,77.5,197601,2748,ME,OC